InfoTag reusable
Anto-MSHK/podhod_front pull request #11
Opened 2023-03-29 18:42 UTC by DULCETq

2023-03-29 19:13 UTC, YourecMart commented on src/components/InfoTag/InfoTag.tsx
>  };
Как я понял, нам этот кусок кода вообще не нужен, тем более написан кринжово через ifы. По моему надо вообще пересмотреть этот компонент, вместе обсудить

2023-03-30 13:09 UTC, Anto-MSHK requested changes
Неверно понял задачу.
Я не зря написал, что принимает только 3 пропса:
- цвет
- текст
- иконку если надо
Не нужен никакой type, status...
Логики выбора цвета не должно быть. Нужен тебе complited - прокидываешь пропсы "green", "icon_complited", "завершено". Нужно просто тип события показать? Прокидываешь цвет по умолчанию, или какой хочешь, без иконки и с текстом "Выставка", например.

2023-04-03 18:13 UTC, YourecMart approved these changes

2023-04-03 22:05 UTC, Anto-MSHK approved these changes

2023-04-04 05:56 UTC, YourecMart approved these changes

2023-04-04 05:56 UTC, merged