Loading Screen fix
Anto-MSHK/podhod_front pull request #14
Opened 2023-03-29 21:53 UTC by S1lveRain

Расширен массив до 500 элементов для поддержки высоких значений диагонали и разрешений, скрыт скроллбар при загрузке ( после загрузки overflow переходит в auto ), добавлено обязательное поле isLoading для Loading Screen.

2023-03-29 21:57 UTC, S1lveRain commented
Обнаружил пару косяков, пофикшу

2023-03-29 22:29 UTC, S1lveRain commented
Косяки пофикшены, всё работает стабильно

2023-03-30 10:51 UTC, YourecMart requested changes

2023-03-30 10:51 UTC, YourecMart commented on src/components/LoadingScreen/LoadingScreen.module.css
Короче хз, мне кажется все таки надо рассчитывать количество кружков в зависимости размера контейнера или viewportа, а еще Никита ты не заблочил скролл во время загрузки

2023-04-02 09:46 UTC, S1lveRain commented on src/components/LoadingScreen/LoadingScreen.module.css
Всё исправил, скроллбар пропадает только при isLoading = true, так что зациклить через EventEdit LoadingScreen не вариант. Для проверки работоспособности в инструментах разработчика укажи медленное 3G соединение - скроллбар появится ровно в тот момент, когда придут данные с сервера и isLoading отвалится в false

2023-04-03 18:12 UTC, YourecMart approved these changes

2023-04-03 19:34 UTC, Anto-MSHK approved these changes

2023-04-03 19:34 UTC, merged