EventForm with dictionary
Anto-MSHK/podhod_front pull request #15
Opened 2023-04-04 07:21 UTC by YourecMart

Сделал словарь для formInput, но не уверен, что использовал лучшее решение для маппинга, проблема в том, что импуты находятся в разных дивка.

2023-04-04 17:34 UTC, S1lveRain reviewed
Не понимаю, зачем два условия сходятся в единице, разве так должно быть?

2023-04-04 17:34 UTC, S1lveRain commented on src/components/EventForm/EventForm.tsx
> +                    index <= 1 &&
Не лучше ли использовать index < 1?

2023-04-04 17:34 UTC, S1lveRain commented on src/components/EventForm/EventForm.tsx
> +                    index >= 1 &&
Не лучше ли использовать index >= 2?

2023-04-04 17:40 UTC, S1lveRain requested changes
Ещё опечатку поправь

2023-04-04 17:40 UTC, S1lveRain commented on src/components/EventForm/EventForm.tsx
> +      lable: "Название",
label вместо lable

2023-04-04 17:40 UTC, S1lveRain commented on src/components/EventForm/EventForm.tsx
> +    lable: string,
label вместо lable

2023-04-04 17:40 UTC, S1lveRain commented on src/components/EventForm/EventForm.tsx
> +                      label={value.lable}
label вместо lable

2023-04-04 17:40 UTC, S1lveRain commented on src/components/EventForm/EventForm.tsx
> +                      label={value.lable}
label вместо lable

2023-04-05 14:48 UTC, S1lveRain submitted a review, later dismissed
Чел хорош

2023-04-05 15:53 UTC, S1lveRain approved these changes
Теперь хорош

2023-04-05 21:02 UTC, Anto-MSHK approved these changes

2023-04-05 21:02 UTC, merged