BottonMenu с Gallery
Anto-MSHK/podhod_front pull request #27
Opened 2023-04-20 10:41 UTC by DULCETq

2023-04-20 18:54 UTC, S1lveRain requested changes
![image](https://user-images.githubusercontent.com/62508833/233461105-3e9447f3-294c-41d6-896f-a1f8ed97c062.png)

2023-04-20 18:56 UTC, S1lveRain submitted a review, later dismissed

2023-04-21 07:58 UTC, Anto-MSHK requested changes
не прощаю
нужно чтобы отображалось всё красиво

2023-04-21 08:19 UTC, S1lveRain commented
> не прощаю
> нужно чтобы отображалось всё красиво

Там вопрос в высоте контейнера, я это поправил, после мерджа всё будет красиво с адаптацией

2023-04-21 08:31 UTC, S1lveRain commented
Всё не будет красиво и с адаптацией. Нужно дать возможность галлерее вылезать за контейнер, тогда красиво будет

2023-05-01 08:55 UTC, Anto-MSHK requested changes
не соответствует макету.

2023-05-15 09:22 UTC, YourecMart approved these changes

2023-05-16 09:22 UTC, merged