PriceForm
Anto-MSHK/podhod_front pull request #32
Opened 2023-04-28 17:04 UTC by DULCETq

2023-04-28 18:25 UTC, S1lveRain requested changes
<img width="1792" alt="Снимок экрана 2023-04-28 в 21 21 28" src="https://user-images.githubusercontent.com/62508833/235224751-27aaf01e-023d-4359-b04f-dc02052f837b.png">
Вопрос только по вот этим ошибкам, в остальном клево выглядит, работает

2023-05-01 08:27 UTC, Anto-MSHK requested changes
Всё супер, но надо подвязать API и добавить на страницу выставки:
![image](https://user-images.githubusercontent.com/70766783/235428764-d2aa853d-3435-4072-af4d-b71288513146.png)

API уже лежит и документировано:
http://194.67.121.107:5000/docs#/Events/EventController_updatePrices

2023-05-07 10:19 UTC, S1lveRain requested changes
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/62508833/236671639-5a5c2371-c200-4e87-89b9-89842d95d2f9.png">
Баг с submit пофиксить

Ещё было бы неплохо сделать fetch имеющихся в данный момент цен с возможностью их удаления

2023-05-07 10:20 UTC, S1lveRain commented
> <img alt="image" width="1460" src="https://user-images.githubusercontent.com/62508833/236671639-5a5c2371-c200-4e87-89b9-89842d95d2f9.png">
> 
> Баг с submit пофиксить
> Ещё было бы неплохо сделать fetch имеющихся в данный момент цен с возможностью их удаления

У тебя форма хоть и пишет ошибку, мол это не число и так нельзя, однако она втихую всё-равно шлёт невалидный запрос на сервер

2023-05-07 10:23 UTC, S1lveRain commented
В кнопку добавления делаешь в onClick условие price && handle...

2023-05-07 11:40 UTC, DULCETq commented
Это еще не все

2023-05-07 11:41 UTC, S1lveRain commented
Угрозы?

2023-05-08 06:25 UTC, YourecMart commented
еще надо стараться следовать принципу single responsibility,  компонента форм не должна что-то отрисовывать и выводить, это не ее задача, ее задача просто запрос отправить с каким-то данными. А то что она из localstorage мапит какие-то цены....
<img width="754" alt="image" src="https://user-images.githubusercontent.com/63181187/236749682-bf5cff3b-7b17-423b-af67-f72b4055224b.png">

2023-05-08 08:53 UTC, DULCETq commented
Этого нет уже

2023-05-08 10:46 UTC, YourecMart commented
все еще выводить цены это не задача компоненты form
<img width="586" alt="image" src="https://user-images.githubusercontent.com/63181187/236803328-da6f801c-3675-445a-b736-e99b68f9d9aa.png">
если кнопка сабмитит форму, ей надо задать type="submit", даже браузер ругается, если не так
<img width="695" alt="image" src="https://user-images.githubusercontent.com/63181187/236803671-d98e9c5d-0322-4654-937d-8fd2e477a5f5.png">
удаление должно быть реализовано запросом, шо толку только локально удалять
<img width="490" alt="image" src="https://user-images.githubusercontent.com/63181187/236803925-bae8a026-c588-4fc3-8260-676f446ab41d.png">
не понял назначение этой функции, которая пропсом прокидывается
<img width="396" alt="image" src="https://user-images.githubusercontent.com/63181187/236804846-6a1bf1be-cb97-460f-92d6-38716f741c57.png">

2023-05-11 09:59 UTC, S1lveRain submitted a review, later dismissed

2023-05-11 11:09 UTC, merged